FROM centos:7.2.1511

RUN yum install -y tcsh epel-release \
    && yum install -y scons gcc-c++ gcc-gfortran mariadb mariadb-devel mariadb-libs \
    && yum install -y libX11-devel mesa-libGLU-devel libXt-devel libXmu-devel libXrender-devel expat-devel libXpm-devel libXft-devel libAfterImage libAfterImage-devel libXi \    
    && yum install -y cmake wget subvesion subversion git make file xorg-x11-fonts-Type1 mesa-dri-drivers xkeyboard-config yumex \
    && yum install -y perl-DBD-MySQL \   
    && rpm -i http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el6/en/x86_64/rpmforge/RPMS/perl-Math-MatrixReal-2.05-1.el6.rf.noarch.rpm \
    && rpm -i http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el6/en/x86_64/rpmforge/RPMS/perl-Math-VectorReal-1.02-1.2.el6.rf.x86_64.rpm \
    && yum install -y tighervnc tighervnc-server fluxbox xterm
