FROM centos:7.2.1511
RUN yum install -y tcsh epel-release 
RUN yum install -y scons gcc-c++ gcc-gfortran mariadb mariadb-devel mariadb-libs libX11-devel mesa-libGLU-devel libXt-devel libXmu-devel libXrender-devel expat-devel libXpm-devel libXft-devel libAfterImage libAfterImage-devel libXi 
RUN yum install -y cmake wget subvesion git make file xorg-x11-fonts-Type1 mesa-dri-drivers xkeyboard-config

